### ISSUE TITLE
Add info on built-in Reporter Plugins and Custom Formatters

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#128]
There's a `/implementations/ruby/custom-formatters`
Should we also add information on formatters / plugins for Java and Javascript?

**Comment by aslakhellesoy** [comment]
I think we should have a `reporter-plugins` page where we document built-in formatter plugins (progress, pretty, html etc) as well as linking to common 3rd party plugins, such as cucumber pro and masterthought.

This would be a polyglot page, since there are some inconsistencies between implementations.

**Comment by mlvandijk** [comment]
I propose unlinking `/implementations/ruby/custom-formatters` from `cucumber.md` in the mean time (see also #117 )

**Comment by mlvandijk** [comment]
Fixed in #189

**Comment by nelsonthedev** [comment]
It just mentions that there are built-in reporters, but not how to use them. Is there a page for that? Say, I want html report to be generated using built in reporter, how do I do that?

**Comment by luke-hill** [comment]
@leonardonelson91 the formatters are being overhauled to use protocol buffers going forwards. More information will arrive when some of the significant changes have landed
