### ISSUE TITLE
HTML Proofer retry?

### ISSUE THREAD

**Issue by mlvandijk** [cucumber/docs#30]
Sometimes the build fails due to (randomly) failing external links.
It would be nice if we could configure HTML Proofer to (for instance) retry 2-3 times if a check on a particular links fails

**Comment by mlvandijk** [comment]
Had a look at https://github.com/gjtorikian/html-proofer
Didn't see an immediate option to retry failed external links, but it is possible to "enable caching for your external links. Caching simply means to skip links that are valid for a certain period of time." (See: Configuring caching)
This would be really useful imho, as atm deploy fails on random external links...

@aslakhellesoy @plaindocs What do you think? (And, if you like it, how long should the timeperiod be set for?)

**Comment by plaindocs** [comment]
Sounds good. We'd have to check the implications of running on Travis CI though, as by default they recreate the environment every build - so we'd need to tweak cache settings. 

48 hours should weed out the ones failing sporadically?

**Comment by mlvandijk** [comment]
48 hours sounds great!
I'm not so familiar with Travis CI or Ruby / config. Who could do it?

**Comment by plaindocs** [comment]
I'll take a look next week.

**Comment by aslakhellesoy** [comment]
External links are only checked on Netlify - it's too slow and annoying to do locally.

It occasionally fails because of timeouts, but a rerun usually fixes it. I think that's good enough for now.

I haven't figured out what directory Netlify uses for caching, so I'm not sure how to take advantage of HTMLProofer's `cache` option. I suggest we close this issue and revisit it if it becomes too much of a nuisance.

**Comment by mlvandijk** [comment]
Agreed. Won't fix (at least for now)
