### ISSUE TITLE
Gherkin language changelog

### ISSUE THREAD

**Issue by drweb86** [cucumber/docs#542]
Hello guys!

I've been updating Gherkin in my project from 5th version to 15. But I cannot find across the Internet what's changed in the language, i.e. what language features I can use from now on in gherkin-javascript.

I guess the same question other guys might erupt since there's no changelog.

Can you please point to me to some direction where to search it for.

Thanks!

**Comment by luke-hill** [comment]
https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md

**Comment by drweb86** [comment]
@luke-hill , may I ask you to confirm that since version 5 to v.15, language changes were (apart from other efforts)
- **Rule** for **Scenario** grouping
- Scenario has synonyms **Scenario Outline**, **Example**

**Comment by luke-hill** [comment]
Yep. Rule came in v6, that was the last big proper breaking change.

Since then many of the breaking changes of gherkin involve updating the usage / versions of cucumber messages, which is our new event protocol for streaming how the flow of a cucumber scenario "works".

There are also some synonyms as mentioned as well. it's not quite correct to say they're (Scenario / Scenario outline), synonyms, more that a scenario can have an examples table now (So you don't need to alter the scenario term to scenario outline).

**Comment by aslakhellesoy** [comment]
The only grammar change is the addition of the Rule keyword and the Scenario synonyms.
All other changes are related to the API of the library.

**Comment by drweb86** [comment]
@luke-hill , @aslakhellesoy , thank you for your answers!

You're doing a great work with cucumber and Gherkin. Personally, I enjoy the simplicity of BDD, it both concentrates the knowledge of how the system is working and used for testing at the same time.
